### ISSUE TITLE
gtk-update-icon-cache: The generated cache was invalid.

### ISSUE THREAD

**Issue by yochananmarqos** [chrisjbillington/git_nautilus_icons#11]
I'm creating a PKGBUILD for the [AUR](https://aur.archlinux.org/) and ran into an issue because the SVG's have spaces in the filenames. See [this issue](https://github.com/OrancheloTeam/oranchelo-icon-theme/issues/9) for reference.
```
==> Installing package git-nautilus-icons-git with pacman -U...

:: Running post-transaction hooks...
(1/2) Updating icon theme caches...
gtk-update-icon-cache: The generated cache was invalid.
error: command failed to execute correctly
```
As in the above linked issue, I was able to successfully update the icon cache:
```
# cd /usr/share/icons
# for f in $(ls */index.theme | sed 's,/index.theme$,,' ) ; do echo $f ; gtk-update-icon-cache -f $f || echo XXX $f XXX ; echo ; done
```
I ended up adding this to my PKGBUILD to temporarily fix the issue:
```
	cd icons/hicolor/scalable/emblems
	for file in *; do
		mv "$file" `echo $file | tr ' ' '-'` ;
	done
```
Could you add dashes instead of spaces?

**Comment by chrisjbillington** [comment]
Thanks for the bug report and for making the AUR package! This should be fixed in 5dd3e98bed.

**Comment by yochananmarqos** [comment]
That was quick, thanks! Yes, it should be fixed. For some reason I'm still getting the same error. I can't figure it out. I'll take a break and look at it again later, I guess.

**Comment by chrisjbillington** [comment]
Oh, it looks like I missed one of the places there could be spaces. Will fix.

**Comment by chrisjbillington** [comment]
Ok, should be better now!

**Comment by yochananmarqos** [comment]
Yep, that did the trick! I added extensions for all three file managers: https://aur.archlinux.org/pkgbase/git-nautilus-icons-git/

**Comment by chrisjbillington** [comment]
Awesome!

Slight snag installing the Nautilus variant - install conflicts with python2-nautilus since it depends on python-nautilus. I'm using python2-nautilus because tortoisehg's nautilus extension is still Python2. So installing this one means editing the PKGBUILD to require python2-nautilus instead.

You look more familiar with making PKGBUILDs than I am, do you know if there's a way to say that it depends on either python-nautilus or python2-nautilus? Since there's no common 'provides' in the two nautilus-python's, it seems trickier than usual.

If not, perhaps a pinned comment on the AUR entry would be nice.

**Comment by yochananmarqos** [comment]
No, there's no way to specify either/or in dependencies. I added a separate Python 2 package to the pkgbase, `git-nautilus-icons-py2-git`.

**Comment by chrisjbillington** [comment]
Sweet, that works great!
