### ISSUE TITLE
option to adjust icon sizes

### ISSUE THREAD

**Issue by stevenxxiu** [chrisjbillington/git_nautilus_icons#13]
Thanks for this plugin, the icon sizes are very small however when I first tried it today, can there be an option to make them bigger? As you can see they are barely visible here.

![Untitled](https://user-images.githubusercontent.com/2058940/57982693-20741780-7a8c-11e9-9afd-e05003ba7925.png)

**Comment by chrisjbillington** [comment]
The icons are smaller than usual emblems because they incorporate both staged and unstaged changes, so they are leaving room to put two icons in the space where there would normally be only one icon. So they are half the size of regular nautilus overlays.

In your example since all the files are clean, there are no separate staged/unstaged statuses, so in this case they are unnecessarily small. But I think I would not want it to make the icons bigger *only* in this case, because then when there are more complex statuses the user might not see the icons because they would be smaller than they are used to. So I think I want at least consistently sized icons no matter whether the file statuses are simple (only clean or unstaged changes) or complex.

But, with the nautilus icons at the absolute minimum size in list view as you have them, the detailed statuses with multiple sub-icons for staged vs unstaged changes are a bit pointless. There is no way to actually see all that information at this size.

So I think the solution to your problem might be to have a 'simple' mode, in which there is no distinction between staged and unstaged changes, with either change counting as 'modified'. Then I could make the icons twice as big, it would look more like this:

![image](https://user-images.githubusercontent.com/1044087/57984845-c7759680-7a2d-11e9-811b-6e0f4267d091.png)

Alternately I could have the extension ship icons that specify their size such that at smaller sizes they would not include the detailed statuses. This second option is probably better than having a user-configurable setting for it.

**Comment by stevenxxiu** [comment]
Thanks for the quick reply!

Indeed the simple mode looks good, a bit like tortoisegit (I'm quite used to it on windows and thinking of switching to linux soon). 

For the second option do you mean that at larger sizes they will include the full status but at smaller size they won't? Yes that seems more ideal like you said.

I'll be happy with either.

**Comment by chrisjbillington** [comment]
Yes, exactly. I will provide 8x8 icons in the icon package, that will be simplified. Then if nautilus renders the icons small, they will be in 'simple mode' and if it renders larger icons they will be more detailed. I'll just need to draw one more icon (a simplified 'merge conflict' icon), and then write the code that decides what the appropriate 'simplified' icon will be for each status.

**Comment by chrisjbillington** [comment]
I have implemented this now, however it doesn't quite work correctly because the 'hicolor' icon theme does not allow for 8x8 icons. I've made a merge request [here](https://gitlab.freedesktop.org/xdg/default-icon-theme/merge_requests/1/) to fix this in the hicolor icon theme. Pending that, you can edit the file `/usr/share/icons/hicolor/index.theme` to make the change that allows 8x8 icons (note, long line of diff snipped for clarity):

```diff
diff --git a/index.theme b/index.theme
index ec5a2f2..8715dcd 100644
--- a/index.theme
+++ b/index.theme
@@ -2,9 +2,20 @@
 Name=Hicolor
 Comment=Fallback icon theme
 Hidden=true
-Directories=16x16/actions,16x16@2/actions,16x16/animations, <snip>
+Directories=8x8/emblems,8x8@2/emblems,16x16/actions,16x16@2/actions,16x16/animations, <snip>

 
+[8x8/emblems]
+Size=8
+Context=Emblems
+Type=Threshold
+
+[8x8@2/emblems]
+Size=8
+Scale=2
+Context=Emblems
+Type=Threshold
+
 [16x16/actions]
 Size=16
 Context=Actions

```
 If the hicolor index.theme is patched as above, then the result looks like this:

![image](https://user-images.githubusercontent.com/1044087/63980810-b1df2680-ca8a-11e9-8209-73d4bf1437c6.png)

Otherwise the full sized icons are downscaled and used, which looks the same as your initial screenshot.

**Comment by stevenxxiu** [comment]
Awesome, thank you so much for the work on this! I needed the patch too, but it works now. Hopefully they merge your PR soon.
