### ISSUE TITLE
Needs updating for Gnome 44

### ISSUE THREAD

**Issue by DarkXero-dev** [chrisjbillington/git_nautilus_icons#24]
Installed both -git n regular from AUR to no avail, icons won't show.. Maybe update needed ? ArchLinux / Gnome 44

**Comment by chrisjbillington** [comment]
Yes, it seems the nautilus extension interface is totally different now.

I will look into this when I have the chance, in the meantime if anyone familiar would like to summarise what needs to be changed, or contribute any patches, that would be most welcome.

**Comment by chrisjbillington** [comment]
Ah, looks like the main issue was simple, just needed to allow the newer version of the API (I was seeing an error from a different extension that made me think the problem was trickier).

Fixed and released as v2.1.0.

There's still some issue with only the simplified icons being displayed, at least on my system, with the newer Nautilus views, but that's a separate issue.

**Comment by DarkXero-dev** [comment]
Thanks it works now. Will include this on my Gnome edition of XeroLinux I am the creator .. You have saved my behind..
